name: Docs

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Set up Pages
      uses: actions/configure-pages@v5
    - name: Generate Docs
      run: |
        swift package --allow-writing-to-directory docs \
        generate-documentation --target MarkovTextGenerator \
        --disable-indexing \
        --transform-for-static-hosting \
        --hosting-base-path markov-text-generator \
        --output-path docs
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v4